name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Compile LaTeX
      uses: dante-ev/latex-action@v0.2.0
      with:
        root_file: relatório/relatório.tex
        working_directory: relatório
        args: "-xelatex -synctex=1 -interaction=nonstopmode -file-line-error"
    - name: Generate build artifact
      uses: actions/upload-artifact@v1
      with:
        name: relatório
        path: relatório/relatório.pdf
