name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Compile LaTeX
      uses: xu-cheng/latex-action@1.2.1
      with:
        root_file: relatório.tex
        working_directory: relatório
        args: "-xelatex -synctex=1 -interaction=nonstopmode -file-line-error"
        extra_system_packages: "ttf-liberation"
    - name: Generate build artifact
      uses: actions/upload-artifact@v1
      with:
        name: relatório
        path: relatório/relatório.pdf
